import UiBuilder from "@/components/UiBuilderComponents/UiBuilder";

export default async function UiBuilderPage() {
  const containerA = null;

  const containerB = {
        "_id": "68bd628b7f82936d80ba82ef",
        "name": "Container",
        "container_Id": "yr3sn9m9j",
        "sectionId": "",
        "type": "div",
        "text": "testfunda",
        "author": "68bd30cc7f82936d80ba3657",
        "projectName": "testFunda - Portfolio",
        "styles": {
          "height": "100px",
          "width": "75%",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderColor": "#cccccc",
          "boxSizing": "border-box",
          "padding": "4px",
          "margin": "0px",
          "backgroundColor": "#ffffff",
          "color": "#000000",
          "display": "flex",
          "flexDirection": "row",
          "justifyContent": "center",
          "alignItems": "center",
          "gap": "0px",
          "flexWrap": "wrap",
          "position": "relative",
          "minHeight": "fit-content",
          "maxWidth": "100%",
          "textAlign": "center",
          "wordWrap": "break-word",
          "lineHeight": "1rem",
          "fontSize": "0.75rem",
          "fontWeight": "400",
          "borderRadius": "0px",
          "boxShadow": "none",
          "cursor": "pointer",
          "opacity": "1",
          "zIndex": "0",
          "transition": "all 0.2s ease"
        },
        "hoverStyles": {
          "backgroundColor": "transparent",
          "color": "transparent",
          "borderColor": "transparent",
          "opacity": "100",
          "scale": "100",
          "boxShadow": "none"
        },
        "linkUrl": "",
        "linkTarget": "_self",
        "linkTitle": "",
        "isClickable": false,
        "imageUrl": "",
        "imageAlt": "",
        "imageMode": "none",
        "imagePosition": "center",
        "imageSize": "cover",
        "imageRepeat": "no-repeat",
        "iconName": "",
        "iconSize": "16",
        "iconColor": "transparent",
        "hasIcon": false,
        "locked": false,
        "hidden": false,
        "children": [
          {
            "name": "Container",
            "container_Id": "9ig839pff",
            "sectionId": "",
            "type": "div",
            "text": "testfunda",
            "author": "68bd30cc7f82936d80ba3657",
            "projectName": "Untitled Project",
            "styles": {
              "height": "100px",
              "width": "100px",
              "borderWidth": "1px",
              "borderStyle": "solid",
              "borderColor": "#cccccc",
              "boxSizing": "border-box",
              "padding": "4px",
              "margin": "0px",
              "backgroundColor": "#ffffff",
              "color": "#000000",
              "display": "flex",
              "flexDirection": "row",
              "justifyContent": "center",
              "alignItems": "center",
              "gap": "0px",
              "flexWrap": "wrap",
              "position": "relative",
              "minHeight": "fit-content",
              "maxWidth": "100%",
              "textAlign": "center",
              "wordWrap": "break-word",
              "lineHeight": "1rem",
              "fontSize": "0.75rem",
              "fontWeight": "400",
              "borderRadius": "0px",
              "boxShadow": "none",
              "cursor": "pointer",
              "opacity": "1",
              "zIndex": "0",
              "transition": "all 0.2s ease"
            },
            "hoverStyles": {
              "backgroundColor": "transparent",
              "color": "transparent",
              "borderColor": "transparent",
              "opacity": "100",
              "scale": "100",
              "boxShadow": "none"
            },
            "linkUrl": "",
            "linkTarget": "_self",
            "linkTitle": "",
            "isClickable": false,
            "imageUrl": "",
            "imageAlt": "",
            "imageMode": "none",
            "imagePosition": "center",
            "imageSize": "cover",
            "imageRepeat": "no-repeat",
            "iconName": "",
            "iconSize": "16",
            "iconColor": "transparent",
            "hasIcon": false,
            "locked": false,
            "hidden": false,
            "_id": "68bd628b7f82936d80ba82f0",
            "children": [null, null, null, null],
            "createdAt": "2025-09-07T10:46:35.398Z",
            "updatedAt": "2025-09-07T10:46:35.398Z"
          },
          {
            "name": "Container",
            "container_Id": "8qas1qomm",
            "sectionId": "",
            "type": "div",
            "text": "testfunda",
            "author": "68bd30cc7f82936d80ba3657",
            "projectName": "Untitled Project",
            "styles": {
              "height": "100px",
              "width": "100px",
              "borderWidth": "1px",
              "borderStyle": "solid",
              "borderColor": "#cccccc",
              "boxSizing": "border-box",
              "padding": "4px",
              "margin": "0px",
              "backgroundColor": "#ffffff",
              "color": "#000000",
              "display": "flex",
              "flexDirection": "row",
              "justifyContent": "center",
              "alignItems": "center",
              "gap": "0px",
              "flexWrap": "wrap",
              "position": "relative",
              "minHeight": "fit-content",
              "maxWidth": "100%",
              "textAlign": "center",
              "wordWrap": "break-word",
              "lineHeight": "1rem",
              "fontSize": "0.75rem",
              "fontWeight": "400",
              "borderRadius": "0px",
              "boxShadow": "none",
              "cursor": "pointer",
              "opacity": "1",
              "zIndex": "0",
              "transition": "all 0.2s ease"
            },
            "hoverStyles": {
              "backgroundColor": "transparent",
              "color": "transparent",
              "borderColor": "transparent",
              "opacity": "100",
              "scale": "100",
              "boxShadow": "none"
            },
            "linkUrl": "",
            "linkTarget": "_self",
            "linkTitle": "",
            "isClickable": false,
            "imageUrl": "",
            "imageAlt": "",
            "imageMode": "none",
            "imagePosition": "center",
            "imageSize": "cover",
            "imageRepeat": "no-repeat",
            "iconName": "",
            "iconSize": "16",
            "iconColor": "transparent",
            "hasIcon": false,
            "locked": false,
            "hidden": false,
            "_id": "68bd628b7f82936d80ba82f1",
            "children": [null, null, null, null],
            "createdAt": "2025-09-07T10:46:35.398Z",
            "updatedAt": "2025-09-07T10:46:35.398Z"
          },
          {
            "name": "Container",
            "container_Id": "tgs8ses9l",
            "sectionId": "",
            "type": "div",
            "text": "testfunda",
            "author": "68bd30cc7f82936d80ba3657",
            "projectName": "Untitled Project",
            "styles": {
              "height": "100px",
              "width": "75%",
              "borderWidth": "1px",
              "borderStyle": "solid",
              "borderColor": "#cccccc",
              "boxSizing": "border-box",
              "padding": "4px",
              "margin": "0px",
              "backgroundColor": "#342d2d",
              "color": "#000000",
              "display": "flex",
              "flexDirection": "row",
              "justifyContent": "center",
              "alignItems": "center",
              "gap": "0px",
              "flexWrap": "wrap",
              "position": "relative",
              "minHeight": "fit-content",
              "maxWidth": "100%",
              "textAlign": "center",
              "wordWrap": "break-word",
              "lineHeight": "1rem",
              "fontSize": "0.75rem",
              "fontWeight": "400",
              "borderRadius": "0px",
              "boxShadow": "none",
              "cursor": "pointer",
              "opacity": "1",
              "zIndex": "0",
              "transition": "all 0.2s ease"
            },
            "hoverStyles": {
              "backgroundColor": "transparent",
              "color": "transparent",
              "borderColor": "transparent",
              "opacity": "100",
              "scale": "100",
              "boxShadow": "none"
            },
            "linkUrl": "",
            "linkTarget": "_self",
            "linkTitle": "",
            "isClickable": false,
            "imageUrl": "",
            "imageAlt": "",
            "imageMode": "none",
            "imagePosition": "center",
            "imageSize": "cover",
            "imageRepeat": "no-repeat",
            "iconName": "",
            "iconSize": "16",
            "iconColor": "transparent",
            "hasIcon": false,
            "locked": false,
            "hidden": false,
            "_id": "68bd628b7f82936d80ba82f2",
            "children": [
              {
                "name": "Container",
                "container_Id": "98hx1ko7m",
                "sectionId": "",
                "type": "div",
                "text": "testfunda",
                "author": "68bd30cc7f82936d80ba3657",
                "projectName": "Untitled Project",
                "styles": {
                  "height": "100px",
                  "width": "100px",
                  "borderWidth": "1px",
                  "borderStyle": "solid",
                  "borderColor": "#cccccc",
                  "boxSizing": "border-box",
                  "padding": "4px",
                  "margin": "0px",
                  "backgroundColor": "#ffffff",
                  "color": "#000000",
                  "display": "flex",
                  "flexDirection": "row",
                  "justifyContent": "center",
                  "alignItems": "center",
                  "gap": "0px",
                  "flexWrap": "wrap",
                  "position": "relative",
                  "minHeight": "fit-content",
                  "maxWidth": "100%",
                  "textAlign": "center",
                  "wordWrap": "break-word",
                  "lineHeight": "1rem",
                  "fontSize": "0.75rem",
                  "fontWeight": "400",
                  "borderRadius": "0px",
                  "boxShadow": "none",
                  "cursor": "pointer",
                  "opacity": "1",
                  "zIndex": "0",
                  "transition": "all 0.2s ease"
                },
                "hoverStyles": {
                  "backgroundColor": "transparent",
                  "color": "transparent",
                  "borderColor": "transparent",
                  "opacity": "100",
                  "scale": "100",
                  "boxShadow": "none"
                },
                "linkUrl": "",
                "linkTarget": "_self",
                "linkTitle": "",
                "isClickable": false,
                "imageUrl": "",
                "imageAlt": "",
                "imageMode": "none",
                "imagePosition": "center",
                "imageSize": "cover",
                "imageRepeat": "no-repeat",
                "iconName": "",
                "iconSize": "16",
                "iconColor": "transparent",
                "hasIcon": false,
                "locked": false,
                "hidden": false,
                "_id": "68bd628b7f82936d80ba82f3",
                "children": [null, null, null, null],
                "createdAt": "2025-09-07T10:46:35.396Z",
                "updatedAt": "2025-09-07T10:46:35.396Z"
              },
              {
                "name": "Container",
                "container_Id": "va0ykf0fc",
                "sectionId": "",
                "type": "div",
                "text": "testfunda",
                "author": "68bd30cc7f82936d80ba3657",
                "projectName": "Untitled Project",
                "styles": {
                  "height": "100px",
                  "width": "100px",
                  "borderWidth": "1px",
                  "borderStyle": "solid",
                  "borderColor": "#cccccc",
                  "boxSizing": "border-box",
                  "padding": "4px",
                  "margin": "0px",
                  "backgroundColor": "#ffffff",
                  "color": "#000000",
                  "display": "flex",
                  "flexDirection": "row",
                  "justifyContent": "center",
                  "alignItems": "center",
                  "gap": "0px",
                  "flexWrap": "wrap",
                  "position": "relative",
                  "minHeight": "fit-content",
                  "maxWidth": "100%",
                  "textAlign": "center",
                  "wordWrap": "break-word",
                  "lineHeight": "1rem",
                  "fontSize": "0.75rem",
                  "fontWeight": "400",
                  "borderRadius": "0px",
                  "boxShadow": "none",
                  "cursor": "pointer",
                  "opacity": "1",
                  "zIndex": "0",
                  "transition": "all 0.2s ease"
                },
                "hoverStyles": {
                  "backgroundColor": "transparent",
                  "color": "transparent",
                  "borderColor": "transparent",
                  "opacity": "100",
                  "scale": "100",
                  "boxShadow": "none"
                },
                "linkUrl": "",
                "linkTarget": "_self",
                "linkTitle": "",
                "isClickable": false,
                "imageUrl": "",
                "imageAlt": "",
                "imageMode": "none",
                "imagePosition": "center",
                "imageSize": "cover",
                "imageRepeat": "no-repeat",
                "iconName": "",
                "iconSize": "16",
                "iconColor": "transparent",
                "hasIcon": false,
                "locked": false,
                "hidden": false,
                "_id": "68bd628b7f82936d80ba82f4",
                "children": [null, null, null, null],
                "createdAt": "2025-09-07T10:46:35.398Z",
                "updatedAt": "2025-09-07T10:46:35.398Z"
              },
              null, null],
            "createdAt": "2025-09-07T10:46:35.398Z",
            "updatedAt": "2025-09-07T10:46:35.398Z"
          },
          null],
        "createdAt": "2025-09-07T10:46:35.400Z",
        "updatedAt": "2025-09-07T10:46:35.400Z",
        "__v": 0
      }


  return (
    <div className="w-full flex flex-col ">
      <UiBuilder initialContainer={containerA} />
    </div>
  );
}
